### ISSUE TITLE
As a user I want to be able to exit the browse page modal when I click outside of it, so that I don't have to reach for the "close button" every time.

### ISSUE THREAD

**Issue by hanshank** [yamovie/client#233] opened 2019-05-09 18:30 UTC

**Comment by hanshank** [comment] 2019-05-09 18:39
Noticed that I automatically tried to exit by clicking outside of the modal, probably because I am used to it from other sites.

**Comment by samsaksfithian** [comment] 2019-05-17 16:37
Duplicate of #79

**Closed by samsaksfithian** 2019-05-17 16:37 UTC
Labels: duplicate, feature, front end, priority 3 - low
